//! Seed the **first Developer-authorized pending Admin + its registration invitation** on a
//! deployed/owner Postgres — spec 009 T10 operator provisioning (docs/runbooks/deploy-admin-web.md →
//! "seed the first admin"). The production analog of `seed_worker_test_b1_pg.rs`, driven by
//! `scripts/seed-admin-invite.sh`. It is what stands in for the Developer-minting UI (spec 001
//! T08-shell, out of scope here): an operator the Developer trusts runs it once per admin to mint the
//! single-use onboarding link Sarah (the Admin persona) uses to register her passkey.
//!
//! It drives the **existing, proven** core store methods (P4 — no parallel store, no schema change):
//!   * no `SEED_ADMIN_ID` → `create_pending_admin_with_invitation` mints a brand-new pending Admin
//!     (role `admin`, **no PII** — null name/address/phone) + its first live invitation, and writes
//!     the DB-minted admin id to `SEED_ADMIN_ID_OUT` so the wrapper can print it. Exit **0**.
//!   * `SEED_ADMIN_ID` set → `reissue_admin_invitation` (atomic supersede-then-insert) re-invites that
//!     existing pending Admin: the prior live invitation is consumed and a fresh one minted, so the
//!     `admin_invitations_one_live_per_admin` index is never violated (idempotent re-run, R19). Exit
//!     **3** (re-invited) — or **4** if no such pending Admin exists (a clear operator error).
//!
//! The invitation token's **at-rest hash is computed in the core** (`admin_invitation_token_hash`,
//! P4 — never a hand-rolled SQL/openssl blob) under the Worker's per-instance `HMAC_KEY`, so the
//! deployed Worker's `resolve_invitation_by_token` matches the very token the operator hands out. The
//! **plaintext token is generated by the wrapper and passed in via the env — it never reaches this
//! process's stdout, a file, or an argv** (R20); only its hash is persisted, and only the non-secret
//! admin id is written to `SEED_ADMIN_ID_OUT`.
//!
//! `created_by` (the I11 audit actor) is left as the schema default (NULL): there is no Developer
//! WebAuthn identity to attribute the mint to until the minting UI lands — a documented audit-actor
//! gap (DEFERRED spec 009 T10 → R18/F5), not silently dropped.
//!
//! Exit code (no stdout/stderr — the pre-commit lint forbids print macros in non-test Rust, and an
//! example is not `cfg(test)`; the wrapper maps the code to an operator message):
//! - `0` — a new pending Admin + invitation was created (`SEED_ADMIN_ID` unset).
//! - `3` — an existing pending Admin was re-invited (fresh token minted, prior superseded).
//! - `4` — `SEED_ADMIN_ID` named no pending Admin in this Group (nothing minted).
//! - non-zero/panic — a bad URL / HMAC key / connection / FK (the `.expect`s below; e.g. the Group's
//!   `groups` row must exist first — run `bootstrap-group.sh`).
//!
//! Env (set by `scripts/seed-admin-invite.sh`; secrets ride in the env, never an argv):
//! - `SEED_OWNER_URL` — the DB OWNER DIRECT URL incl. `?sslmode=require` (neondb_owner; its BYPASSRLS
//!   lands the insert under FORCE RLS, exactly like `bootstrap-group.sh`). NOT `boundless_app`.
//! - `SEED_GROUP_ID` — the Group uuid (this install's `GROUP_ID` Worker binding).
//! - `SEED_HMAC_KEY_HEX` — the 64-char-hex per-instance HMAC key; MUST equal the Worker's `HMAC_KEY`
//!   secret (else the Worker can never resolve the minted token).
//! - `SEED_INVITE_TOKEN` — the plaintext invitation token (the wrapper's `openssl rand -hex 32`).
//! - `SEED_EXPIRES_AT_SECS` / `SEED_NOW_SECS` — absolute UnixSeconds (the wrapper computes them, so
//!   this example draws no ambient clock — the same discipline as the core's injected `Clock`).
//! - `SEED_ADMIN_ID` — optional: re-invite this existing pending Admin instead of creating one.
//! - `SEED_ADMIN_ID_OUT` — a file path; on a create, the new admin id (a non-secret uuid) is written
//!   here for the wrapper to print. (Only the admin id — never the token — touches a file.)

use boundless_auth::UnixSeconds;
use boundless_crypto::{admin_invitation_token_hash, HmacKey};
use boundless_domain::{AdminInvitationToken, MemberId};
use boundless_server_core::AdminProvisioningStore;
use boundless_server_store::PgAuthStore;
use std::process::ExitCode;
use uuid::Uuid;

#[tokio::main(flavor = "current_thread")]
async fn main() -> ExitCode {
    let url = env("SEED_OWNER_URL");
    let group_id: Uuid = env("SEED_GROUP_ID")
        .parse()
        .expect("SEED_GROUP_ID must be a uuid");
    let key = HmacKey::from_bytes(hex32(&env("SEED_HMAC_KEY_HEX")));
    let token = AdminInvitationToken::new(env("SEED_INVITE_TOKEN"));
    let expires_at = UnixSeconds::new(env_i64("SEED_EXPIRES_AT_SECS"));
    let now = UnixSeconds::new(env_i64("SEED_NOW_SECS"));

    // The at-rest hash the Worker matches — computed in the core under the Worker's HMAC key (P4). The
    // plaintext token never leaves this fn (only its hash is persisted).
    let token_hash = admin_invitation_token_hash(&key, &token);

    // Neon REQUIRES TLS (`sslmode=require`). native-tls verifies the server cert against the OS trust
    // store (no MITM — we never set `danger_accept_invalid_*`); the SAME connector serves a local
    // no-TLS Postgres (`sslmode=disable`) — the meta-test path. tokio-postgres honors the URL's
    // `sslmode` itself. (Identical to `bootstrap_group_pg.rs`.)
    let tls = native_tls::TlsConnector::new().expect("build the TLS connector");
    let connector = postgres_native_tls::MakeTlsConnector::new(tls);
    let (client, conn) = tokio_postgres::connect(&url, connector)
        .await
        .expect("connect to the owner DB (use the DIRECT/unpooled endpoint, as neondb_owner)");
    tokio::spawn(async move {
        let _ = conn.await;
    });

    let mut store = PgAuthStore::new(client, group_id);

    match std::env::var("SEED_ADMIN_ID").ok().filter(|s| !s.trim().is_empty()) {
        // Re-invite an existing pending Admin (lost/expired link): supersede-then-insert (R19).
        Some(raw) => {
            let admin_id = MemberId::from_uuid(raw.trim().parse().expect("SEED_ADMIN_ID must be a uuid"));
            let existed = store
                .reissue_admin_invitation(admin_id, token_hash, expires_at, now)
                .await
                .expect("re-invite the pending Admin (is the Group bootstrapped? run bootstrap-group.sh)");
            if existed {
                ExitCode::from(3) // re-invited — fresh token minted, prior superseded
            } else {
                ExitCode::from(4) // no such pending Admin in this Group — nothing minted
            }
        }
        // Mint a brand-new pending Admin + its first invitation.
        None => {
            let admin_id = store
                .create_pending_admin_with_invitation(token_hash, expires_at)
                .await
                .expect("create the pending Admin (is the Group's `groups` row present? run bootstrap-group.sh)");
            // Hand the (non-secret) admin id back to the wrapper via the out-file — never stdout (the
            // lint) and never alongside the token. `std::fs::write` is a plain write, not a print macro.
            let out = env("SEED_ADMIN_ID_OUT");
            std::fs::write(&out, format!("{}\n", admin_id.as_uuid()))
                .unwrap_or_else(|e| panic!("write the admin id to SEED_ADMIN_ID_OUT ({out}): {e}"));
            ExitCode::SUCCESS // 0 — created
        }
    }
}

fn env(k: &str) -> String {
    std::env::var(k).unwrap_or_else(|_| panic!("{k} must be set"))
}

fn env_i64(k: &str) -> i64 {
    env(k).trim().parse().unwrap_or_else(|_| panic!("{k} must be an integer (unix seconds)"))
}

/// Decode a 64-char hex string into 32 bytes (the HMAC key).
fn hex32(s: &str) -> [u8; 32] {
    let s = s.trim();
    assert_eq!(s.len(), 64, "HMAC key hex must be exactly 64 chars (32 bytes)");
    let mut out = [0u8; 32];
    for (i, slot) in out.iter_mut().enumerate() {
        *slot = u8::from_str_radix(&s[2 * i..2 * i + 2], 16).expect("HMAC key must be valid hex");
    }
    out
}
