#!/usr/bin/env bash
# Boundless — (re)generate the committed API bindings and refresh the drift lock (ADR-0001).
#
# Spec 001 task T10 FROZE the contracts (api/openapi.yaml, api/boundless.proto) + the AC7
# tests. The real codegen (swift-openapi-generator, openapi-generator kotlin, openapi-typescript
# + ts-proto, and the UniFFI XCFramework/AAR) is wired in T10-shell, per target, alongside the
# consuming UI tasks (T11–T15) once those toolchains are available — see DEFERRED.md. Until then
# this runs in SCAFFOLD MODE: it ensures the generated tree exists and (re)writes
# api/.bindings.lock from the current contracts/core + generated tree — so the drift gate
# (scripts/check-binding-drift.sh) is already live.
#
# Run this after any change to api/openapi.yaml, api/boundless.proto, or core/**, then
# commit the updated api/.bindings.lock (and, from T10 on, the regenerated outputs).
set -euo pipefail
cd "$(dirname "$0")/.."
# shellcheck source=scripts/_bindings_common.sh
. scripts/_bindings_common.sh

LOCK=api/.bindings.lock
mkdir -p api/generated/swift api/generated/kotlin api/generated/typescript

# ─── T10-shell inserts real generators here (per target, with T11–T15) ──────────────
echo "ℹ generate-bindings: scaffold mode (contracts frozen in T10; real codegen lands in T10-shell)."

{
    echo "# Boundless binding-drift lock — DO NOT EDIT BY HAND."
    echo "# Regenerated by scripts/generate-bindings.sh; verified by scripts/check-binding-drift.sh."
    echo "# sha256 of contract inputs (api/ + core/) and generated outputs (api/generated/)."
    echo "[inputs]"
    bindings_input_files | bindings_hash_list
    echo "[outputs]"
    bindings_output_files | bindings_hash_list
} >"$LOCK"

echo "✓ wrote $LOCK. Commit it alongside your change."
