#!/usr/bin/env bash
# Seed the first Developer-authorized pending Admin + its single-use registration invitation on a
# deployed/owner Postgres — spec 009 T10 operator provisioning (docs/runbooks/deploy-admin-web.md →
# "seed the first admin"). This stands in for the Developer-minting UI (spec 001 T08-shell, deferred):
# an operator the Developer trusts runs it once per admin to mint the onboarding link the Admin (Sarah)
# uses to register her passkey. There is still NO signup/self-serve path (I11/ADR-0015).
#
# It drives examples/seed_admin_invite_pg.rs, which reuses the proven core store methods:
#   * no admin-id  → mints a NEW pending Admin (role admin, NO PII — null name/address/phone) + invite.
#   * an admin-id  → RE-INVITES that existing pending Admin (atomic supersede-then-insert; the prior
#                    live invite is consumed, a fresh one minted — the one-live index is upheld, R19).
#                    Use this to re-issue a lost/expired link without creating a second admin.
#
# The token's at-rest hash is computed IN THE CORE under your per-instance HMAC key (P4), so the
# deployed Worker resolves the very token printed here. The plaintext token is generated by THIS script
# and printed ONLY to stdout — never an argv, never a file, never a stderr log line (R20). The owner URL
# and the HMAC key ride in the ENV (never an argv), so neither appears in `ps`/shell history.
#
# Connect as the database OWNER (Neon's `neondb_owner`, DIRECT/unpooled endpoint): its BYPASSRLS lands
# the insert under FORCE RLS (exactly like bootstrap-group.sh; the runtime `boundless_app` role can't).
# The Group's `groups` row must already exist — run `scripts/bootstrap-group.sh` first.
#
# Usage:
#   SEED_OWNER_URL=<owner-url> SEED_HMAC_KEY_HEX=<64-hex> bash scripts/seed-admin-invite.sh <group-id> [admin-id]
#   # e.g. (mint the first admin):
#   SEED_OWNER_URL="postgresql://neondb_owner:PW@HOST/neondb?sslmode=require" \
#   SEED_HMAC_KEY_HEX="$HMAC_KEY" \
#     bash scripts/seed-admin-invite.sh 00000000-0000-0000-0000-000000000001
#   # re-invite an existing pending admin (fresh link):
#   SEED_OWNER_URL=… SEED_HMAC_KEY_HEX=… bash scripts/seed-admin-invite.sh <group-id> <admin-id>
#
# Optional env:
#   SEED_HMAC_KEY_HEX   the per-instance HMAC key; MUST equal the Worker's `HMAC_KEY` secret (step 4 of
#                       deploy-worker.md), or the Worker can never resolve the token you hand out.
#   SEED_INVITE_TTL_SECS  invite lifetime in seconds (default 259200 = 72h, the store's documented default).
#   SEED_ADMIN_WEB_BASE   the deployed admin-web origin (e.g. https://boundless-admin-web.<acct>.workers.dev);
#                         when set, the full onboarding URL is printed, else just the path.
set -euo pipefail

log() { echo "$@" >&2; }
fail() { echo "✗ $1" >&2; exit 1; }

GROUP_ID="${1:-}"
ADMIN_ID="${2:-}"
OWNER_URL="${SEED_OWNER_URL:-}"
HMAC_HEX="${SEED_HMAC_KEY_HEX:-}"
TTL_SECS="${SEED_INVITE_TTL_SECS:-259200}"   # 72h, matching create_pending_admin_with_invitation's default

usage="usage: SEED_OWNER_URL=<owner-url> SEED_HMAC_KEY_HEX=<64-hex> seed-admin-invite.sh <group-id> [admin-id]"
[ -n "$GROUP_ID" ]  || { log "$usage"; exit 2; }
[ -n "$OWNER_URL" ] || fail "SEED_OWNER_URL must be set (the owner DB URL; via env so it is not in \`ps\`)"
case "$OWNER_URL" in postgres://*|postgresql://*) : ;; *) fail "SEED_OWNER_URL must be a postgres:// connection string" ;; esac
# group-id (and admin-id, if given) must be uuid-shaped (8-4-4-4-12 hex).
is_uuid() { case "$1" in
  [0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]-[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]-[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]-[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]-[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]) return 0 ;; *) return 1 ;; esac; }
is_uuid "$GROUP_ID" || fail "group-id must be a uuid (e.g. 00000000-0000-0000-0000-000000000001)"
[ -z "$ADMIN_ID" ] || is_uuid "$ADMIN_ID" || fail "admin-id (optional 2nd arg) must be a uuid"
# HMAC key must be exactly 64 hex chars (32 bytes). Validate before any work (clearer than a Rust panic).
case "$HMAC_HEX" in
  ""|*[!0-9a-fA-F]*) fail "SEED_HMAC_KEY_HEX must be the 64-char-hex HMAC key (the value you \`wrangler secret put HMAC_KEY\`)" ;;
esac
[ "${#HMAC_HEX}" -eq 64 ] || fail "SEED_HMAC_KEY_HEX must be exactly 64 hex chars (32 bytes); got ${#HMAC_HEX}"
case "$TTL_SECS" in ''|*[!0-9]*) fail "SEED_INVITE_TTL_SECS must be a positive integer (seconds); got '${TTL_SECS}'" ;; esac
# Reject 0 too: a zero/negative TTL mints an invite already expired at creation — a dead-on-arrival link
# whose later failure (the Worker rejecting it as expired) is far from this cause.
[ "$TTL_SECS" -gt 0 ] || fail "SEED_INVITE_TTL_SECS must be a positive integer (seconds); got '${TTL_SECS}' — a zero TTL mints an already-expired invite"
command -v openssl >/dev/null 2>&1 || fail "openssl not found on PATH (needed to generate the invite token)"

# A redacted scheme://host/db for logging — NEVER the userinfo (P2: the owner password must not reach
# logs). Greedy `.*@` strips ALL userinfo (robust even with '@' in the password); then drop any `?query`.
safe_url="$(printf '%s' "$OWNER_URL" | sed -E 's#^(postgres(ql)?://).*@#\1#; s#\?.*$##')"
case "$safe_url" in
  *-pooler.*) log "⚠ this looks like a POOLED endpoint ('-pooler'). Use the DIRECT (unpooled) owner endpoint if the insert fails." ;;
esac

# Fresh 256-bit opaque token (the provision-neon.sh entropy precedent). It is a SECRET: it is held only
# in this variable + the env handed to the helper + printed to stdout. It is NEVER logged (stderr).
TOKEN="$(openssl rand -hex 32)"
NOW_SECS="$(date +%s)"
EXPIRES_AT_SECS=$((NOW_SECS + TTL_SECS))

if [ -n "$ADMIN_ID" ]; then
  log "→ re-inviting pending Admin ${ADMIN_ID} in Group ${GROUP_ID} on ${safe_url} (as the database owner)"
else
  log "→ minting a new pending Admin + invitation in Group ${GROUP_ID} on ${safe_url} (as the database owner)"
fi

SERVER_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../server" && pwd)"
log "→ building the seed helper…"
( cd "$SERVER_DIR" && cargo build -q -p boundless-server-store --example seed_admin_invite_pg ) \
  || fail "failed to build the seed example"
TARGET_DIR="${CARGO_TARGET_DIR:-${SERVER_DIR}/target}"
BIN="${TARGET_DIR}/debug/examples/seed_admin_invite_pg"
[ -x "$BIN" ] || fail "built binary not found at ${BIN} (CARGO_TARGET_DIR override?)"

# A throwaway file for the helper to hand back the NEW admin id (non-secret) on a create — never the
# token. Cleaned up on exit.
ID_OUT="$(mktemp)"
trap 'rm -f "$ID_OUT"' EXIT

# Run the binary DIRECTLY (not `cargo run`) so its exact exit code reaches us — 0=created, 3=re-invited,
# 4=no-such-admin, else=error. ALL secrets (owner URL, HMAC key, token) ride in the env, never an argv.
set +e
SEED_OWNER_URL="$OWNER_URL" \
SEED_GROUP_ID="$GROUP_ID" \
SEED_HMAC_KEY_HEX="$HMAC_HEX" \
SEED_INVITE_TOKEN="$TOKEN" \
SEED_EXPIRES_AT_SECS="$EXPIRES_AT_SECS" \
SEED_NOW_SECS="$NOW_SECS" \
SEED_ADMIN_ID="$ADMIN_ID" \
SEED_ADMIN_ID_OUT="$ID_OUT" \
  "$BIN"
code=$?
set -e

case "$code" in
  0) ADMIN_ID="$(tr -d '[:space:]' < "$ID_OUT")"
     [ -n "$ADMIN_ID" ] || fail "the helper reported success but wrote no admin id"
     log "✓ minted a new pending Admin (no PII) + a live invitation (expires in ${TTL_SECS}s)." ;;
  3) log "✓ re-invited pending Admin ${ADMIN_ID} — a fresh link was minted and the prior one superseded (expires in ${TTL_SECS}s)." ;;
  4) fail "no pending Admin ${ADMIN_ID} exists in Group ${GROUP_ID} — omit the admin-id to mint a NEW pending Admin." ;;
  *) fail "seed failed (exit ${code}). Check the owner URL (DIRECT endpoint, neondb_owner), the HMAC key (64-hex, matching the Worker's secret), and that the Group is bootstrapped (run bootstrap-group.sh; the \`groups\` row must exist)." ;;
esac

# The single-use onboarding link. Printed ONLY here, ONLY to stdout (R20). Hand it to the admin out of
# band; it is consumed on her first successful passkey registration.
if [ -n "${SEED_ADMIN_WEB_BASE:-}" ]; then
  ONBOARD="${SEED_ADMIN_WEB_BASE%/}/admin/onboard/${TOKEN}"
else
  ONBOARD="/admin/onboard/${TOKEN}   (prefix your deployed admin-web origin; or set SEED_ADMIN_WEB_BASE)"
fi
echo "admin_id=${ADMIN_ID}"
echo "token=${TOKEN}"
echo "onboard_url=${ONBOARD}"
